### ISSUE TITLE
Assertion error when input dim equals dim size

### ISSUE THREAD

**Issue by alkalait** [pangeo-data/xbatcher#16]
Suppose for `DataArray` `x`, `x.shape==(10, 1000, 1000)`, with `dims=('time', 'y', 'x')`.

In that case
`bgen = xbatcher.BatchGenerator(x, input_dims={'time':10, 'y': 500, 'x':500})`
gives an assertion error at
https://github.com/pangeo-data/xbatcher/blob/8c29bcf90eb678c29f1020122f44cb9a5e59e431/xbatcher/generators.py#L22

As it stands now, it's tricky to define a batch size where a batch dimension size equals that dimension's size.

I think this use-case could be simpler to implement by simply changing the line above to
`assert stride <= dimsize `.

**Comment by jhamman** [comment]
closed by #21

**Comment by jhamman** [comment]
also, thanks for the report @alkalait!
