### ISSUE TITLE
Can you point me towards a full demo?

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/xbatcher#26]
I'm so happy to see such progress on xbatcher in recent months.

On Sept. 8 I am giving a presentation to the [M2LiNES](https://m2lines.github.io/) group, and I'd like to give a demo of xbatcher. Does anyone have a full demo / example using public data that can be shared? It's okay if it's messy or whatever--I can clean it up as needed.

Thanks!

**Comment by jhamman** [comment]
closed by #31?
