### ISSUE TITLE
bug when working on a dimension with no coordinate

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/xbatcher#3]
I am getting errors from these lines

https://github.com/rabernat/xbatcher/blob/e728bd29b54147e6a3463407c41af4f4b629eaec/xbatcher/generators.py#L44-L45

When working on a POP dataset with input dimensions `nlat, nlon` with no coordinates. I believe it boils down to.
```
>>> xr.DataArray([0, 0, 0], dims=['x']).drop('x')
ValueError: One or more of the specified variables cannot be found in this dataset
```

Solution would be to only drop if the variable actually exists.

**Comment by jhamman** [comment]
closed by e8853739d512d7fea45eb4d69bd8fa8163d9519e
