### ISSUE TITLE
Type error in iteration routines

### ISSUE THREAD

**Issue by cmdupuis3** [pangeo-data/xbatcher#34]
Not sure what's really going on here, but from this bit of code,

    bgen = xb.BatchGenerator(
        ds,
        {'nlon':nlons,     'nlat':nlats},
        {'nlon':(nlons/2), 'nlat':(nlats/2)},
        concat_input_dims = True
    )

    for batch in bgen:
        model.fit([batch[x] for x in (sc.stencil_2D + sc.stencil_3D + sc.vanilla)],
                  [batch[x] for x in sc.target],
                  batch_size=32, epochs=2,
                  callbacks=[history, tf.keras.callbacks.TerminateOnNaN()])

I eventually get some kind of type error in _slices:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /tmp/ipykernel_461/3742806048.py in <module>
    ----> 1 train(ds_training, scenarios_2D[4])
    
    /tmp/ipykernel_461/2263950181.py in train(ds, sc, conv_dims_2D, conv_dims_3D, nfilters)
         41 
         42     history = LossHistory()
    ---> 43     for batch in bgen:
         44         model.fit([batch[x] for x in (sc.stencil_2D + sc.stencil_3D + sc.vanilla)],
         45                   [batch[x] for x in sc.target],
    
    /srv/conda/envs/notebook/lib/python3.9/site-packages/xbatcher/generators.py in __iter__(self)
        123             if self.concat_input_dims:
        124                 new_dim_suffix = '_input'
    --> 125                 all_dsets = [
        126                     _drop_input_dims(
        127                         ds_input, list(self.input_dims), suffix=new_dim_suffix
    
    /srv/conda/envs/notebook/lib/python3.9/site-packages/xbatcher/generators.py in <listcomp>(.0)
        123             if self.concat_input_dims:
        124                 new_dim_suffix = '_input'
    --> 125                 all_dsets = [
        126                     _drop_input_dims(
        127                         ds_input, list(self.input_dims), suffix=new_dim_suffix
    
    /srv/conda/envs/notebook/lib/python3.9/site-packages/xbatcher/generators.py in _iterate_through_dataset(ds, dims, overlap)
         34         size = dims[dim]
         35         olap = overlap.get(dim, 0)
    ---> 36         dim_slices.append(_slices(dimsize, size, olap))
         37 
         38     for slices in itertools.product(*dim_slices):
    
    /srv/conda/envs/notebook/lib/python3.9/site-packages/xbatcher/generators.py in _slices(dimsize, size, overlap)
         21     assert stride > 0
         22     assert stride <= dimsize
    ---> 23     for start in range(0, dimsize, stride):
         24         end = start + size
         25         if end <= dimsize:
    
    TypeError: 'float' object cannot be interpreted as an integer

**Comment by jhamman** [comment]
Thanks @cmdupuis3 for opening an issue. Can you report what the values are for this bit of your code example:

```python
    {'nlon':(nlons/2), 'nlat':(nlats/2)},
```

I suspect the division here is resulting in floating point values.

**Comment by cmdupuis3** [comment]
Both are 20

**Comment by cmdupuis3** [comment]
I'm trying out casting them to ints, seems to be working so far...

**Comment by jhamman** [comment]
But they are floating point values:

```ipython
In [1]: nlats = 40

In [2]: {'nlats': nlats/2}
Out[2]: {'nlats': 20.0}

In [3]: type({'nlats': nlats/2}['nlats'])
Out[3]: float

In [4]: type(nlats/2)
Out[4]: float
```

Try casting those values to ints: 

```python
    {'nlon': int(nlons/2), 'nlat': int(nlats/2)},

```
