### ISSUE TITLE
Support xarray.DataArray and xarray.Dataset batches in PyTorch dataloader

### ISSUE THREAD

**Issue by maxrjones** [pangeo-data/xbatcher#84]
As discussed in https://github.com/pangeo-data/xbatcher/pull/71#discussion_r950377393_, the PyTorch DataLoader should be extended to support either dataarray or dataset batches after the batch generator output was generalized in https://github.com/pangeo-data/xbatcher/pull/71.

**Comment by weiji14** [comment]
I can work on this, got some code already to improve the [`.torch` accessor](https://github.com/pangeo-data/xbatcher/blob/714b6244a5fc47b9e01afb7a1805cee3b1670224/xbatcher/accessors.py#L29-L48), can you assign me this issue?

**Comment by maxrjones** [comment]
> I can work on this, got some code already to improve the [`.torch` accessor](https://github.com/pangeo-data/xbatcher/blob/714b6244a5fc47b9e01afb7a1805cee3b1670224/xbatcher/accessors.py#L29-L48), can you assign me this issue?

Super, thanks! Assigned
